### ISSUE TITLE
A tip for selecting multiple notes

### ISSUE THREAD

**Issue by randomwangran** [ag91/escalator#1]
Thanks for writing the helm source for =org-roam=. 

https://github.com/ag91/escalator/blob/dcfabb26c99ae187cd0100f358c8fd97e92bebdb/escalator.el#L152-L159

If someone is interested in inserting multiply links, the following code should be okay.

Just using `C-SPACE` to mark the notes, then users could insert those notes in one shot.

```elisp
("Insert links" . (lambda (x)
                    (let ((note (helm-marked-candidates :with-wildcard t)))
                      (cl-loop for n in note
                               do (--> n
                                       org-roam-node-from-title-or-alias
                                       (insert
                                        (format
                                         "[[id:%s][%s]]\n"
                                         (org-roam-node-id it)
                                         (org-roam-node-title it))))))))
```

**Comment by ag91** [comment]
That is a great idea. Maybe you can add it as an extra action with a PR? I think an extra action because of the extra `\n` (newline)

**Comment by randomwangran** [comment]
Hi Andrea @ag91 :

I have no problem making a PR, but I do not know what's your
preference for inserting multiply notes.

I use your code mainly to insert them as a part of `org-transclusion`
[package](https://github.com/nobiot/org-transclusion). You can see a visual example of how I do [that](https://github.com/randomwangran/roam-with-helm). The
illustration was written for `org-roam` version 1, but the concept is
the same. `org-transclusion` has restrictions on the format of note, so
I hard code your source into something like this [repo.](https://github.com/randomwangran/roam-with-helm/blob/3658243b90a98ea7e839dcf3a43e60efc9fd631f/roam-with-helm-v2.el)

Please let me your thoughts, I will see what I can do for you.

Best regards,

Ran

**Comment by ag91** [comment]
Ah it looks amazing Ran! I think it is amazing that you integrated the helm searcher in your repo with the extra actions you needed. 
No need then of the PR then, I will add the actions myself if needed and refer to your repo when I do, so that people can get only the Roam related bits :)

Thanks again for sharing!

Andrea

**Comment by randomwangran** [comment]
You're welcome. 

Thanks for sharing the blog post for this source.

I will just close this issue now. Please let me know if you have further questions.
